export const goalList = [
	{
		id: 1,
		goal: 'Sessions',
		dataName: 'sessions',
		inputType: 'number',
	},
	{
		id: 2,
		goal: 'Avg. Session Time (mins.)',
		dataName: 'sessionsAvgTime',
		inputType: 'number',
	},
	{
		id: 3,
		goal: 'Website CTR (%)',
		dataName: 'ctr',
		inputType: 'number',
	},
	{
		id: 4,
		goal: 'Website ER (%)',
		dataName: 'er',
		inputType: 'number',
	},
	{
		id: 5,
		goal: 'Leads',
		dataName: 'leads',
		inputType: 'number',
	},
	{
		id: 6,
		goal: 'Leads Growth Rate (%)',
		dataName: 'leadRate',
		inputType: 'number',
	},
	{
		id: 7,
		goal: 'Cost-Per-Leads ($)',
		dataName: 'costPerLead',
		inputType: 'number',
	},
	{
		id: 8,
		goal: 'Conversions',
		dataName: 'conversions',
		inputType: 'number',
	},
	{
		id: 9,
		goal: 'Conversion Growth Rate (%)',
		dataName: 'conversionRate',
		inputType: 'number',
	},
	{
		id: 10,
		goal: 'Cost-Per-Conversions ($)',
		dataName: 'costPerConversion',
		inputType: 'number',
	},
	{
		id: 11,
		goal: 'Budget',
		dataName: 'budgetTotal',
		inputType: 'number',
	},
	{
		id: 12,
		goal: 'Expense',
		dataName: 'expenseTotal',
		inputType: 'number',
	},
	{
		id: 13,
		goal: 'Facebook Followers',
		dataName: 'followers',
		inputType: 'number',
	},
	{
		id: 14,
		goal: 'Facebook Page Views',
		dataName: 'pageViews',
		inputType: 'number',
	},
	{
		id: 15,
		goal: 'Website CTR (%)',
		dataName: 'ctr',
		inputType: 'number',
	},
	{
		id: 16,
		goal: 'Website ER (%)',
		dataName: 'er',
		inputType: 'number',
	},
	{
		id: 17,
		goal: 'Leads',
		dataName: 'leads',
		inputType: 'number',
	},
	{
		id: 18,
		goal: 'Leads Growth Rate (%)',
		dataName: 'leadRate',
		inputType: 'number',
	},
	{
		id: 19,
		goal: 'Cost-Per-Leads ($)',
		dataName: 'costPerLead',
		inputType: 'number',
	},
	{
		id: 20,
		goal: 'Conversions',
		dataName: 'conversions',
		inputType: 'number',
	},
	{
		id: 21,
		goal: 'Conversion Growth Rate (%)',
		dataName: 'conversionRate',
		inputType: 'number',
	},
	{
		id: 22,
		goal: 'Cost-Per-Conversions ($)',
		dataName: 'costPerConversion',
		inputType: 'number',
	},
	{
		id: 23,
		goal: 'Budget',
		dataName: 'budgetTotal',
		inputType: 'number',
	},
	{
		id: 24,
		goal: 'Expense',
		dataName: 'expenseTotal',
		inputType: 'number',
	},
];
